name: Fetch Secret

on:
  push:
    branches:
      - main

jobs:
  fetch-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch Secret
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "Secret API key fetched successfully."
